<testResult cycle="001" cvus="000" thread="001" suite="TestLauncelot" name="test_dialog"  time="1370964352.93" result="Error" steps="0" duration="0.0375199317932" connection_duration="0.0" requests="0" pages="0" xmlrpc="0" redirects="0" images="0" links="0" traceback='Traceback (most recent call last):&#10;   File "/Users/joy/Code/projects/books/PythonNetworkProgramming/chap07/funkload/lib/python2.7/site-packages/funkload/FunkLoadTestCase.py", line 946, in __call__&#10;    testMethod()&#10;   File "/Users/joy/Code/projects/books/PythonNetworkProgramming/chap07/funkload/launcelot_tests.py", line 9, in test_dialog&#10;    sock.connect((SERVER_HOST, launcelot.PORT))&#10;   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth&#10;    return getattr(self._sock,name)(*args)&#10; error: [Errno 61] Connection refused&#10;' />
